dist: xenial
sudo: required

language: minimal

notifications:
  email:
    - acogoluegnes@pivotal.io
    - knilsson@pivotal.io
addons:
  apt:
    sources:
      - sourceline: deb https://packages.erlang-solutions.com/ubuntu xenial contrib
        key_url: https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc
    packages:
      - esl-erlang=1:21.3.8.1-1
branches:
  only:
    - master

script: make tests

