name: Verify TLA+ Specifications

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  verify-specs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        spec: 
          - { config: "bounded_counter/BoundedCounter.cfg", tla: "bounded_counter/BoundedCounter.tla" }
          - { config: "hybrid_logic_clock/HybridLogicClock.cfg", tla: "hybrid_logic_clock/HybridLogicClock.tla" }
          - { config: "parallel_commits/ParallelCommits.cfg", tla: "parallel_commits/ParallelCommits.tla" }
          - { config: "raft/Raft.cfg", tla: "raft/Raft.tla", timeout: 60 }
    name: Verify ${{ matrix.spec.tla }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Download TLA+ tools
        run: |
          mkdir -p tla
          wget -O tla/tla2tools.jar https://github.com/tlaplus/tlaplus/releases/download/v1.8.0/tla2tools.jar

      - name: Verify TLA+ spec
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            # Manual trigger - run without timeout
            echo "🔄 Manual execution - running without timeout"
            java -XX:+UseParallelGC -jar tla/tla2tools.jar -config ${{ matrix.spec.config }} ${{ matrix.spec.tla }}
          else
            # Automated trigger - use existing timeout logic
            if [ -n "${{ matrix.spec.timeout }}" ]; then
              timeout ${{ matrix.spec.timeout }} java -XX:+UseParallelGC -jar tla/tla2tools.jar -config ${{ matrix.spec.config }} ${{ matrix.spec.tla }} || exit_code=$?
              if [ $exit_code -eq 124 ]; then
                echo "🕒 Timeout reached - marking as passed"
                exit 0
              elif [ $exit_code -ne 0 ]; then
                exit $exit_code
              fi
            else
              java -XX:+UseParallelGC -jar tla/tla2tools.jar -config ${{ matrix.spec.config }} ${{ matrix.spec.tla }}
            fi
          fi
